name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Unity Editor
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2022.3.46f1

      - name: Download Firebase SDK
        run: |
          git clone --depth 1 https://github.com/firebase/quickstart-unity.git
          mkdir Assets/Firebase
          cp -r quickstart-unity/testapp/Assets/Firebase Assets/Firebase

      - name: Run Tests
        run: |
          # Run your Unity tests here
          ./run-tests.sh

  deploy_preview:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy_to_live:
    if: github.event.pull_request.merged == true
    needs: deploy_preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Live Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
