name: Test Unity Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Run Unity Package Tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        packageMode: true
        projectPath: .
        unityVersion: '2022.3.31f1'
        testMode: All
        artifactsPath: artifacts

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test results
        path: artifacts
