name: Build on Push

on:
  push:
    branches:
      - master
      - dev 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Cache Unity Library
      uses: actions/cache@v3
      with:
        path: |
          Library
        key: ${{ runner.os }}-unity-library-${{ hashFiles('**/Packages/manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-unity-library-

    - name: Clean repository
      run: 
        git clean -fdx
        git checkout -- Library

    - name: Set up Firebase Authentication
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT > firebase-service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-service-account.json

    - name: Download Firebase SDK
      run: |
        wget https://firebase.google.com/download/unity -O firebase-unity-sdk.zip
        mkdir -p Assets/Firebase
        unzip firebase-unity-sdk.zip -d Assets/Firebase

    - name: Build Unity Project for Android
      uses: game-ci/unity-builder@v4
      with:
        projectPath: .
        unityVersion: '2022.3.31f1'
        targetPlatform: Android
        buildName: AndroidBuild
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Build artifacts
        path: build