name: Test and Build on Push

on:
  push:
    branches:
        - master
        - dev 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Clean repository
      run: |
          git clean -fdx

    - name: Set up Firebase Authentication
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT > firebase-service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-service-account.json
        # Optionally, initialize Firebase Auth here if needed for tests

    - name: Run Unity Package Tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: .
        unityVersion: '2022.3.31f1'
        testMode: All
        artifactsPath: artifacts

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test results
        path: artifacts

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build Unity Project for Android
      uses: game-ci/unity-builder@v4
      with:
        projectPath: .
        unityVersion: '2022.3.31f1'
        targetPlatform: Android
        buildName: AndroidBuild
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Build artifacts
        path: build
